package appWarung;

import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class appDaftarJualMenu extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB(); 
    
    private DefaultTableModel model;
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getKoneksi();
            Statement stm = conn.createStatement();
            String sql = "SELECT * FROM daftarmenu ORDER BY total DESC";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {
                
                Object[] data = new Object[4];
                data[0] = rs.getString("idMenu");
                data[1] = rs.getString("namaMenu");
                data[2] = rs.getString("hargaa");
                data[3] = rs.getString("total");
                
                model.addRow(data);
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
    }
    
    public void tampil(){
        
        int row = tabelDaftarJualMenu.getRowCount();
        int totall;
        int totalBiaya = 0;
        
        for (int i = 0; i < row; i++) {
            
            totall = Integer.parseInt(tabelDaftarJualMenu.getValueAt(i, 3).toString());
            totalBiaya = totalBiaya + totall;
            
        }
        
        total.setText("Rp " + totalBiaya + ",00");
        
    }
    
    public appDaftarJualMenu() {
        
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelDaftarJualMenu.setModel(model);
        
        model.addColumn("ID Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga");
        model.addColumn("Total");
        
        read();
        tampil();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        keluar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarJualMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalPendapatan = new javax.swing.JLabel();
        total = new javax.swing.JTextField();

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setText("       Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Data Transaksi");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        keluar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(204, 0, 0));
        keluar.setText("     Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Jual Menu");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabelDaftarJualMenu.setBackground(new java.awt.Color(255, 255, 255));
        tabelDaftarJualMenu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelDaftarJualMenu.setForeground(new java.awt.Color(51, 51, 51));
        tabelDaftarJualMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Nama Menu", "Harga", "Total"
            }
        ));
        tabelDaftarJualMenu.setRowHeight(30);
        tabelDaftarJualMenu.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tabelDaftarJualMenu);
        if (tabelDaftarJualMenu.getColumnModel().getColumnCount() > 0) {
            tabelDaftarJualMenu.getColumnModel().getColumn(0).setMinWidth(40);
            tabelDaftarJualMenu.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelDaftarJualMenu.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 250));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Total Pendapatan :");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        totalPendapatan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        totalPendapatan.setForeground(new java.awt.Color(51, 51, 51));
        totalPendapatan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalPendapatanPropertyChange(evt);
            }
        });
        jPanel9.add(totalPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(51, 51, 51));
        total.setText("Rp 0");
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel9.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 318, 320, 30));
        total.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        
    }//GEN-LAST:event_logoutMouseClicked

    private void totalPendapatanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPendapatanPropertyChange
        
    }//GEN-LAST:event_totalPendapatanPropertyChange

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        
        menuUtamaAdmin direct = new menuUtamaAdmin();
        direct.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_keluarMouseClicked

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appDaftarJualMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appDaftarJualMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appDaftarJualMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appDaftarJualMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel logout;
    private javax.swing.JTable tabelDaftarJualMenu;
    private javax.swing.JTextField total;
    private javax.swing.JLabel totalPendapatan;
    // End of variables declaration//GEN-END:variables
}
