package appWarung;

import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class appDaftarMenu extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB(); 
    
    private DefaultTableModel model;
    
    private void autonumber(){
        try {
            
            Connection conn = DB.getKoneksi();
            Statement stm = conn.createStatement();
            String sql = "SELECT * FROM daftarmenu ORDER BY idMenu DESC";
            ResultSet rs = stm.executeQuery(sql);
            
            if (rs.next()) {
                
                String idmenu = rs.getString("idMenu").substring(2);
                String MN = "" +(Integer.parseInt(idmenu)+1);
                String Nol = "";
                
                if (MN.length()==1) 
                    {Nol = "00";}
                else if(MN.length()==2)
                    {Nol = "0";}
                else if(MN.length()==3)
                    {Nol = "";}
                
                id_Menu.setText("MN" + Nol + MN); 
                
            }else{
            
                id_Menu.setText("MN001");
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            System.out.println("autonumber error");
            
        }
    }
    
    public void clear(){
        
        menutipe.setSelectedItem("Pilih Tipe Menu");
        nama_Menu.setText("");
        harga.setText("");
        
    }
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getKoneksi();
            Statement stm = conn.createStatement();
            String sql = "SELECT idMenu, tipeMenu, namaMenu, hargaa FROM daftarmenu";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {
                
                Object[] data = new Object[4];
                data[0] = rs.getString("idMenu");
                data[1] = rs.getString("tipeMenu");
                data[2] = rs.getString("namaMenu");
                data[3] = rs.getString("hargaa");
                
                model.addRow(data);
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
    }
    
    public appDaftarMenu(){
        
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelMenu.setModel(model);
        
        model.addColumn("ID Menu");
        model.addColumn("Tipe Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga");
        
        read();
        autonumber();
        
        id_Menu.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        keluar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id_Menu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        simpan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hapus = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ubah = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        batal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama_Menu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menutipe = new javax.swing.JComboBox<>();

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setText("       Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Data Transaksi");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        keluar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(204, 0, 0));
        keluar.setText("     Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Daftar Menu");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBorder(null);

        tabelMenu.setBackground(new java.awt.Color(255, 255, 255));
        tabelMenu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelMenu.setForeground(new java.awt.Color(51, 51, 51));
        tabelMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nama Menu", "Harga"
            }
        ));
        tabelMenu.setRowHeight(30);
        tabelMenu.setShowHorizontalLines(true);
        tabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMenu);
        if (tabelMenu.getColumnModel().getColumnCount() > 0) {
            tabelMenu.getColumnModel().getColumn(0).setMinWidth(40);
            tabelMenu.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelMenu.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 380, 320));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID Menu : ");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        id_Menu.setBackground(new java.awt.Color(255, 255, 255));
        id_Menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        id_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(id_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Harga : ");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        harga.setBackground(id_Menu.getBackground());
        harga.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        harga.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(51, 51, 51));
        simpan.setText("      Simpan");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        hapus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(51, 51, 51));
        hapus.setText("       Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 80, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        ubah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ubah.setForeground(new java.awt.Color(51, 51, 51));
        ubah.setText("        Ubah");
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        batal.setForeground(new java.awt.Color(51, 51, 51));
        batal.setText("        Batal");
        batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, 30));
        jPanel5.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Menu : ");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        nama_Menu.setBackground(new java.awt.Color(255, 255, 255));
        nama_Menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nama_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(nama_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 230, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nama Menu : ");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        menutipe.setBackground(new java.awt.Color(255, 255, 255));
        menutipe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        menutipe.setForeground(new java.awt.Color(51, 51, 51));
        menutipe.setMaximumRowCount(4);
        menutipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe Menu", "Makanan", "Minuman" }));
        jPanel9.add(menutipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        
    }//GEN-LAST:event_logoutMouseClicked
    
    
    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        
        menuUtamaAdmin direct = new menuUtamaAdmin();
        direct.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_keluarMouseClicked

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        
        int t = tabelMenu.getSelectedRow();
        
        if (t == -1) {
            return;
        }
        
        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = nama_Menu.getText();
        String hargaaa = harga.getText();
        
        if(tipemenu == "Pilih Tipe Menu") {
            
            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");
            
        } else if (nama_Menu.getText().equals("") || harga.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong!");
            
        } else if (nama_Menu.getText().matches("[0-9]*")) {
            
            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus String!");
            
        } else if (!harga.getText().matches("[0-9]*")) {
            
            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");
            
        } else {
        
            int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Mengubah Data?","Konfirmasi", 
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (pernyataan == JOptionPane.OK_OPTION) {

                try {

                    Connection conn = DB.getKoneksi();
                    String sql = "UPDATE daftarmenu SET namaMenu='" + nama_menu +
                            "', tipeMenu='" + tipemenu + "', hargaa='" + hargaaa + "' WHERE idMenu='" + id_menu + "'";
                    Statement pr = conn.createStatement();
                    pr.executeUpdate(sql);

                    pr.close();
                    JOptionPane.showMessageDialog(null, "Menu Berhasil Diubah");

                    simpan.setEnabled(true);
                    ubah.setEnabled(false);
                    hapus.setEnabled(false);
                    batal.setEnabled(false);
                    clear();

                } catch(Exception e) {

                    JOptionPane.showMessageDialog(this, e.getMessage());

                } finally {

                    autonumber();
                    read();

                }

            } if (pernyataan == JOptionPane.CANCEL_OPTION) {

            }
         
        }
        
    }//GEN-LAST:event_ubahMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        
        String id_menu = id_Menu.getText();
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = nama_Menu.getText();
        String hargaaa = harga.getText();
        
        if(tipemenu == "Pilih Tipe Menu") {
            
            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");
            
        } else if (nama_Menu.getText().equals("") || harga.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong!");
            
        } else if (nama_Menu.getText().matches("[0-9]*")) {
            
            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus String!");
            
        } else if (!harga.getText().matches("[0-9]*")) {
            
            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");
            
        } else {
            
            try {
            
                Connection conn = DB.getKoneksi();
                String sql = "INSERT INTO daftarmenu (idMenu, tipeMenu, namaMenu, hargaa) VALUES ('" 
                        + id_menu + "', '" + tipemenu + "', '" + nama_menu + "', " + hargaaa + ");";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);

                pr.close();
                JOptionPane.showMessageDialog(null, "Menu Berhasil Ditambahkan");
                read();

            } catch(Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());

            } finally {

                autonumber();
                clear();

            }
            
        }
        
    }//GEN-LAST:event_simpanMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        
        int t = tabelMenu.getSelectedRow();
        
        if (t == -1) {
            return;
        }
        
        String id_menu = (String) model.getValueAt(t, 0);
        
        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Menghapus Data?","Konfirmasi", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (pernyataan== JOptionPane.OK_OPTION) {
            
            try {
                
                Connection conn = DB.getKoneksi();
                String sql = "DELETE FROM daftarmenu WHERE idMenu ='" + id_menu + "'";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);
                pr.close();
                
                JOptionPane.showMessageDialog(null, "Data Telah Terhapus");
                
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, e.getMessage());
                
            }finally{
                
                simpan.setEnabled(true);
                ubah.setEnabled(false);
                hapus.setEnabled(false);
                batal.setEnabled(false);
                read();
                autonumber();
                clear();
                
            }
            
        }
        
        if (pernyataan== JOptionPane.CANCEL_OPTION) {
            
        }
        
    }//GEN-LAST:event_hapusMouseClicked

    private void batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalMouseClicked
        
        clear();
        read();
        simpan.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);
        autonumber();
        
    }//GEN-LAST:event_batalMouseClicked

    private void tabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMenuMouseClicked
        
        simpan.setEnabled(false);
        ubah.setEnabled(true);
        hapus.setEnabled(true);
        batal.setEnabled(true);
        
        int t = tabelMenu.getSelectedRow();
        
        if (t == -1) {
            return;
        }
        
        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) model.getValueAt(t, 1);
        String nama_menu = (String) model.getValueAt(t, 2);
        String hargaaa = (String) model.getValueAt(t, 3);
        
        id_Menu.setText(id_menu);
        menutipe.setSelectedItem(tipemenu);
        nama_Menu.setText(nama_menu);
        harga.setText(hargaaa);
        
    }//GEN-LAST:event_tabelMenuMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batal;
    private javax.swing.JLabel hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel logout;
    private javax.swing.JComboBox<String> menutipe;
    private javax.swing.JTextField nama_Menu;
    private javax.swing.JLabel simpan;
    private javax.swing.JTable tabelMenu;
    private javax.swing.JLabel ubah;
    // End of variables declaration//GEN-END:variables
}
