package appWarung;

import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class appDataTransaksi extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB(); 
    
    private DefaultTableModel model;
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getKoneksi();
            Statement stm = conn.createStatement();
            String sql = "SELECT username, tipeUser, totalPembelian FROM auth "
                    + "WHERE username != 'admin' ORDER BY totalPembelian DESC";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {
                
                Object[] data = new Object[3];
                data[0] = rs.getString("username");
                data[1] = rs.getString("tipeUser");
                data[2] = rs.getString("totalPembelian");
                
                model.addRow(data);
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
    }
    
    public void tampil(){
        
        int row = tabelDataTransaksi.getRowCount();
        int totall;
        int totalBiaya = 0;
        
        for (int i = 0; i < row; i++) {
            
            totall = Integer.parseInt(tabelDataTransaksi.getValueAt(i, 2).toString());
            totalBiaya = totalBiaya + totall;
            
        }
        
        total.setText("Rp " + totalBiaya + ",00");
        
    }
    
    public appDataTransaksi() {
        
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelDataTransaksi.setModel(model);
        
        model.addColumn("Username");
        model.addColumn("Tipe User");
        model.addColumn("Total Pembelian");
        
        ubah.setEnabled(false);
        
        read();
        tampil();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        keluar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataTransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalPendapatan = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ubah = new javax.swing.JLabel();
        tipeuser = new javax.swing.JComboBox<>();

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setText("       Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Data Transaksi");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        keluar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(204, 0, 0));
        keluar.setText("     Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Transaksi");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabelDataTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        tabelDataTransaksi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelDataTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        tabelDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nama Pembeli", "Total"
            }
        ));
        tabelDataTransaksi.setRowHeight(30);
        tabelDataTransaksi.setShowHorizontalLines(true);
        tabelDataTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataTransaksi);
        if (tabelDataTransaksi.getColumnModel().getColumnCount() > 0) {
            tabelDataTransaksi.getColumnModel().getColumn(0).setMinWidth(40);
            tabelDataTransaksi.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelDataTransaksi.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 250));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Total Pendapatan :");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        totalPendapatan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        totalPendapatan.setForeground(new java.awt.Color(51, 51, 51));
        totalPendapatan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalPendapatanPropertyChange(evt);
            }
        });
        jPanel9.add(totalPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(51, 51, 51));
        total.setText("Rp 0");
        total.setBorder(null);
        jPanel9.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 348, 320, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        ubah.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ubah.setForeground(new java.awt.Color(51, 51, 51));
        ubah.setText("     Ubah");
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 80, 30));

        tipeuser.setBackground(new java.awt.Color(255, 255, 255));
        tipeuser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tipeuser.setForeground(new java.awt.Color(51, 51, 51));
        tipeuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pembeli", "pelanggan" }));
        jPanel9.add(tipeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        
    }//GEN-LAST:event_logoutMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        
        menuUtamaAdmin direct = new menuUtamaAdmin();
        direct.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_keluarMouseClicked

    private void totalPendapatanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPendapatanPropertyChange
        
    }//GEN-LAST:event_totalPendapatanPropertyChange

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        
        int t = tabelDataTransaksi.getSelectedRow();
        
        if (t == -1) {
            return;
        }
        
        String tipeuserr = (String) tipeuser.getSelectedItem();
        String uname = (String) model.getValueAt(t, 0);
        
        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Mengubah Data?","Konfirmasi", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (pernyataan == JOptionPane.OK_OPTION) {

            try {

                Connection conn = DB.getKoneksi();
                String sql = "UPDATE auth SET tipeUser='" + tipeuserr +
                        "' WHERE username='" + uname + "'";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);

                pr.close();
                JOptionPane.showMessageDialog(null, "Menu Berhasil Diubah");

                ubah.setEnabled(false);
                    
            } catch(Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());

            } finally {

                read();

            }

        } if (pernyataan == JOptionPane.CANCEL_OPTION) {

        }
        
    }//GEN-LAST:event_ubahMouseClicked

    private void tabelDataTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataTransaksiMouseClicked
        
        ubah.setEnabled(true);
        
        int t = tabelDataTransaksi.getSelectedRow();
        
        if (t == -1) {
            return;
        }
        
        String tipeuserr = (String) model.getValueAt(t, 1);
        
        tipeuser.setSelectedItem(tipeuserr);
        
    }//GEN-LAST:event_tabelDataTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel logout;
    private javax.swing.JTable tabelDataTransaksi;
    private javax.swing.JComboBox<String> tipeuser;
    private javax.swing.JTextField total;
    private javax.swing.JLabel totalPendapatan;
    private javax.swing.JLabel ubah;
    // End of variables declaration//GEN-END:variables
}
